- name: "pre_task | install packages"
  apt: name={{ item }} state=present
  with_items:
    - wget
    - nano

- name: "pre_task | clean iptables"
  command: iptables -F

- name: "pre_task | Add IP address of all hosts to all hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: "pre_task | Create ssh user for infra"
  user:
    name: "{{ infra_node_ssh_user }}"
    password: "{{ infra_node_ssh_pass | password_hash('sha512') }}"
    groups: 
      - sudo
    append: yes
    create_home: yes
    shell: /bin/bash
    state: present
  when: infra_node_ssh_user != 'root'
  tags:
    - pre_task

- name: "pre_task | Ensure that ssh directory for infra user exist"
  file:
    path: "/home/{{ infra_node_ssh_user }}/.ssh"
    state: directory
    owner: "{{ infra_node_ssh_user }}"
    group: "{{ infra_node_ssh_user }}"
    mode: '0755'
  when: infra_node_ssh_user != 'root'
  tags:
    - pre_task

- name: "pre_task | Upload public ssh key to infra user authorized_keys"
  copy:
    src: "{{ node_source_ssh_keyfile_pub }}"
    dest: "/home/{{ infra_node_ssh_user }}/.ssh/authorized_keys"
    owner: "{{ infra_node_ssh_user }}"
    group: "{{ infra_node_ssh_user }}"
    mode: '0644'
  when: infra_node_ssh_user != 'root'
  tags:
    - pre_task

- name: "pre_task | Allow passwordless sudo to infra user"
  lineinfile:
    dest: "/etc/sudoers.d/{{ infra_node_ssh_user }}"
    state: present
    create: yes
    regexp: '^{{ infra_node_ssh_user }}'
    line: '{{ infra_node_ssh_user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  when: infra_node_ssh_user != 'root'
  tags:
    - pre_task
